port: 9666
cachetime: 60
blacklisttime: 20
collectors:
  - ssh
  - overallstate
sshcollector:
  services:
    - hostd
    - nsx-opsagent
    - nsx-proxy
    - nsxa
    - ntpd
    - vpxa
    - vvold
