port: 9666
collectors:
  critical_service_collector:
    max_threads: 10
    services:
      - hostd
      - nsx-opsagent
      - nsx-proxy
      - nsxa
      - ntpd
      - vpxa
      - vvold
